//ticket State
export const GET_TICKETS = "GET_TICKETS";

export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const FILTER_TICKETS = "FILTER_TICKETS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const CLEAR_TICKETS = "CLEAR_TICKETS";
export const TICKET_ERROR = "TICKET_ERROR";

// admin state

export const ADMIN_ADD_STAFF = "ADMIN_ADD_STAFF";
export const ADMIN_DELETE_USER = "ADMIN_DELETE_USER";
export const ADMIN_ADD_STUDENT = "ADMIN_ADD_STUDENT";
export const ADMIN_GET_ALL_USERS = "ADMIN_GET_ALL_USERS";
export const ADMIN_GET_USER_ROLES = "ADMIN_GET_USER_ROLES";
export const ADMIN_ARCHIVE_TICKET = "ADMIN_ARCHIVE_TICKET";
export const ADMIN_ASSIGN_TICKET = "ADMIN_ASSIGN_TICKET";
export const ADMIN_RESOLVE_TICKET = "ADMIN_RESOLVE_TICKET";
export const ADMIN_REMOVE_ASSIGNED = "ADMIN_REMOVE_ASSIGNED";
export const SET_LOADING = "SET_LOADING";

// users

export const USER_ERROR = "USER_ERROR";

// auth state
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_LOGGEDIN_USER_SUCCESS = "GET_USERROLES_SUCCESS";
export const GET_LOGGEDIN_USER_FAIL = "GET_USERROLES_FAIL";
