//ticket State
export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKETS_FAIL = "GET_TICKETS_FAIL";
export const ADD_TICKET = "ADD_TICKET";
export const ADD_TICKET_FAIL = "ADD_TICKET_FAIL";
export const DELETE_TICKET = "DELETE_TICKET";
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const UPDATE_TICKET_FAIL = "UPDATE_TICKET_FAIL";
export const FILTER_TICKETS = "FILTER_TICKETS";

export const CLEAR_TICKETS = "CLEAR_TICKETS";
export const TICKET_ERROR = "TICKET_ERROR";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_CATEGORIES_FAIL";
export const SET_TICKET_COMMENTS = "SET_TICKET_COMMENTS";
export const SET_ASSIGNED_STAFF = "SET_ASSIGNED_STAFF";
export const SET_TICKET_COMMENTS_MODAL_OPEN = "SET_TICKET_COMMENTS_OPEN";
export const SET_ASSIGNED_STAFF_MODAL_OPEN = "SET_ASSIGNED_STAFF_MODAL_OPEN";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const RESET_FILTER = "RESET_FILTER";

// CRUD Modals
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_DELETE_TICKET_MODAL_OPEN = "SET_DELETE_TICKET_MODAL_OPEN";
export const SET_DELETING_TICKET_ID = "SET_DELETING_TICKET_ID";

// admin state
export const DELETE_USER = "DELETE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_USER_ROLES = "GET_USER_ROLES";
export const ARCHIVE_TICKET = "ARCHIVE_TICKET";
export const ASSIGN_TICKET = "ASSIGN_TICKET";
export const RESOLVE_TICKET = "RESOLVE_TICKET";
export const REMOVE_ASSIGNED = "REMOVE_ASSIGNED";
export const FILTER_USERS = "FILTER_USERS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";

export const ADMIN_FETCH_TICKETS = "ADMIN_FETCH_TICKETS";
export const ADMIN_FILTER_TICKETS = "ADMIN_FILTER_TICKETS";
export const ADMIN_CLEAR_TICKET_FILTER = "CLEAR_TICKET_FILTER";
export const ADMIN_FETCH_TICKET_BY_ID = "ADMIN_FETCH_TICKET_BY_ID";
export const PROMOTE_USER_TO_STAFF = "PROMOTE_USER_TO_STAFF";
export const PROMOTE_ANY_USER = "PROMOTE_ANY_USER";
export const PROMOTE_USER_TO_ADMIN = "PROMOTE_USER_TO_ADMIN";

export const CLEAR_USERS = "CLEAR_USERS";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";

export const SET_LOADING = "SET_LOADING";

export const ADMIN_ERROR = "ADMIN_ERROR";

// users
export const ERROR = "ERROR";

// auth state
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_LOGGEDIN_USER_SUCCESS = "GET_USERROLES_SUCCESS";
export const GET_LOGGEDIN_USER_FAIL = "GET_USERROLES_FAIL";

// Staff
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";
export const GET_ASSIGNED_TICKETS = "GET_ASSIGNED_TICKETS";
export const GET_ASSIGNED_TICKETS_FAIL = "GET_ASSIGNED_TICKETS_FAIL";
export const GET_All_TICKETS = "GET_All_TICKETS";
export const GET_All_TICKETS_FAIL = "GET_All_TICKETS_FAIL";
